### ISSUE TITLE
Support static classes, enums (and I'm guessing structs, interfaces)

### ISSUE THREAD

**Issue by Gitgiddy** [filipw/Strathweb.Roslyn#11]
Non-static classes get the Quick Action but static classes, enums and I'm guessing structs, interfaces don't.  It seems to me that they should also be given this feature.

Thanks!

**Comment by filipw** [comment]
static classes are already supported, see screenshot. But enums don't work atm, good point
perhaps your class was private, private classes are not supported.

<img width="665" alt="screen shot 2015-09-08 at 15 58 07" src="https://cloud.githubusercontent.com/assets/1710369/9736602/760e0074-5642-11e5-9673-aec08fc0d21c.png">

**Comment by Gitgiddy** [comment]
Oh that must have been it.  Is there any reason why private classes can't be supported?

**Comment by filipw** [comment]
no real reason to be honest - it was just modelled after R#, which only allows moving types to new file when they are not private

**Comment by filipw** [comment]
it's a bit of a problem to move private classes, cause what do you do with them? change them to public or internal? what about the rest of the code that references them? what about collisions? Things like that

**Comment by Gitgiddy** [comment]
you mean nested classed or private classes?  I don't see how private classes cause any issues - they would be the same in the new file.

**Comment by filipw** [comment]
private classes can only be nested

**Comment by filipw** [comment]
this PR added support for enums https://github.com/filipw/Strathweb.Roslyn/pull/13

**Comment by Gitgiddy** [comment]
oops, `internal`.

But anyway, I went back to my code sample and I have `public static class MyClass` and it does not get the Quick Action although the `public class` above it and the `internal class` below it DO.

**Comment by filipw** [comment]
can you try on the new project? works on my machine :poodle: 
Also, I pushed version 0.3.0 to vs gallery just now
