### ISSUE TITLE
Messes up my code formatting in the original file after moving the class into new file

### ISSUE THREAD

**Issue by nvmkpk** [filipw/Strathweb.Roslyn#15]

**Comment by tgjones** [comment]
I'm seeing the same issue - it messes up the formatting in both the original and moved file. It's a pity, because otherwise this extension would be really useful!

**Comment by strandloper** [comment]
This issue makes the extension pretty much unusable for me. It's less effort to manually move a class than it is to reformat my code after my formatting has been undone.

**Comment by filipw** [comment]
it's fixed already with #14, just need to release new version

**Comment by filipw** [comment]
it's been released to the VS gallery
