### ISSUE TITLE
No move option in quick actions menu

### ISSUE THREAD

**Issue by strandloper** [filipw/Strathweb.Roslyn#17]
I just updated to version 0,4,0 to take advantage of the fix for [#15](https://github.com/filipw/Strathweb.Roslyn/issues/15) and now I don't see the **Move class to file** option in the Quick Actions menu. Could this be because I am still using Visual Studio 2015 Update 1? A problem with SQL2016 components prevents us from installing Update 2 or 3 at this time.

**Comment by filipw** [comment]
that's true, it needs Update 3 cause of Roslyn 1.3.0 😞 
I am gonna downgrade to 1.0.0 sorry for the trouble!

**Comment by filipw** [comment]
@strandloper hey can you please retry with the new version? https://visualstudiogallery.msdn.microsoft.com/4151b07d-ed17-4158-960b-0c14eae7c330

I downgraded back to Roslyn 1.0.0 so all VS 2015 versions should be supported

**Comment by strandloper** [comment]
Sorry, about the delay; different timezones :-).

It's working fine on VS2015 Update 1 now. Moving the class and not reformatting anything.
