### ISSUE TITLE
Is this still working for the 2015 RC?

### ISSUE THREAD

**Issue by Gitgiddy** [filipw/Strathweb.Roslyn#4]
I suspect it isn't, but I'm new to this plugin.  Very excited about it though, because I hate resharper but this is probably the one part I'd want out of it.

Anyway, when I'm on a public class in a file of a different name with other classes in the same file and press ctrl+. with the cursor on the class name, I only get the "Extract Interface" option.

**Comment by lord-devious** [comment]
I have the same problem.

**Comment by alexandernyquist** [comment]
I'm having the same issue. Going to have a look.

**Comment by Euphoric** [comment]
+1 I cannot seem to get this addin to work. MS VS 2015 Community in Universal Windows type project.

**Comment by alexandernyquist** [comment]
I could not get it to work so I made my own extension, https://github.com/alexandernyquist/MoveToFile.

**Comment by Euphoric** [comment]
Ok. I built this extension myself and it works. Maybe updating the one in VS Gallery would solve this problem.

**Comment by filipw** [comment]
This is fixed now

**Comment by Gitgiddy** [comment]
Please update the source.extension.vsixmanifest version number so Visual Studio will allow the upgrade to run.

**Comment by filipw** [comment]
it was updated in the gallery already, just not committed to source git

**Comment by Gitgiddy** [comment]
Hmm, it didn't work for me as an in-gallery update.  And when I downloaded it manually it said the version was already installed.  I had to uninstall and reinstall with the update I'd already downloaded.  It now correctly shows 0.2 in the about for the installed version now.
