### ISSUE TITLE
Strange output format

### ISSUE THREAD

**Issue by ycrumeyrolle** [filipw/Strathweb.Roslyn#7]
The following class 
```C#
    public abstract class Test7  
    {
        DateTime date;
        Regex regex;

        public abstract void AddRate([NotNull] string rate, [NotNull] string context, [NotNull] string requirement);

        public abstract string GetKey([NotNull] HttpContext httpContext, [NotNull] string requirement);
    }
```

is extracted into 
```C#
    public abstract class Test7
    {
        DateTime date;
        Regex regex;
        public abstract void AddRate(
        [NotNull]
        string rate, [NotNull]
        string context, [NotNull]
        string requirement);
        public abstract string GetKey(
        [NotNull]
        HttpContext httpContext, [NotNull]
        string requirement);
    }
```

The strange format is done by the `NormalizeWhitespace()` method.

Is it a "normal" format ?

**Comment by tg73** [comment]
I'm seeing the same issue, and it's quite a problem. It makes what would otherwise be a great extension close to unusable.

**Comment by ycrumeyrolle** [comment]
It seems to be a Roslyn closed issue.
See https://github.com/dotnet/roslyn/issues/3195

**Comment by tg73** [comment]
Unfortunately, I guess it may be some time before that fix makes it into a VS 2015 update.

What's your reasoning behind calling `NormalizeWhitespace` here? Would it not be preferable to leave the extracted code formatted exactly as it was in the original file (and likewise for the remaining code left in the original file)? Further, `NormalizeWhitespace` applies a set of whitespace rules that will be wrong if the user is not using code formatting equivalent to the VS defaults (as is the case where I work).

**Comment by togakangaroo** [comment]
Whats the deal with the above PR? I just installed and used this extension and it reformatted everything, My understanding of this PR is that it shouldn't have?

**Comment by kellyelton** [comment]
Yeah would be really nice if this was fixed
