### ISSUE TITLE
Update the addon in VS gallery.

### ISSUE THREAD

**Issue by Euphoric** [filipw/Strathweb.Roslyn#9]
The version in VS Gallery doesn't seem to be working.

**Comment by filipw** [comment]
thanks looking into it, I'll upgrade it to stable Roslyn 1.0.0 (it was created based on a pre-release)

**Comment by filipw** [comment]
It's been updated https://visualstudiogallery.msdn.microsoft.com/4151b07d-ed17-4158-960b-0c14eae7c330
